version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=vmessage
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=vmessage
    ports:
      - '5432:5432'
    volumes: 
      - ~/Documents/docker/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ~/Documents/docker/redis/data:/data
volumes:
  db:
    driver: local
